[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
mainnet = "https://singapore.rpc.blxrbdn.com"
bsc = "https://bsc-dataseed.binance.org/"

[etherscan]
mainnet = { key = "" }
bsc = { key = "" }